#!/usr/bin/env python3
"""Tests for kona_scanner_gui.py script.

Note: These tests require tkinter which may not be available in headless CI environments.
Tests will be skipped if tkinter is not available.
"""

import dataclasses
import datetime as dt
import pathlib
import struct
import sys
import zlib
from typing import List

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

# Check for tkinter availability
try:
    import tkinter as tk
    HAS_TKINTER = True
except ImportError:
    HAS_TKINTER = False
    print("Note: tkinter not available, using standalone test implementation")


# Standalone SwatchData for testing without tkinter
@dataclasses.dataclass
class SwatchData:
    """Data for a single Kona swatch."""
    panel: str
    panel_index: int
    id: int
    name: str
    L: float = None
    a: float = None
    b: float = None
    R: int = None
    G: int = None
    B: int = None
    measured: bool = False
    notes: str = ""


# Constants (must match kona_scanner_gui.py)
SCHEMA_VERSION = 1
MAX_ENTRIES = 365
KONA_REF_T_SIZE = 16


def _generate_cpp_standalone(swatches: List[SwatchData], csv_path: str) -> str:
    """Standalone implementation of C++ generation for testing.
    
    This mirrors the logic in KonaScannerApp._generate_cpp() so we can test
    the output format without requiring tkinter.
    """
    # Sort by ID
    sorted_swatches = sorted(swatches, key=lambda s: s.id)
    
    if len(sorted_swatches) > MAX_ENTRIES:
        raise ValueError(f"Too many entries ({len(sorted_swatches)}), max is {MAX_ENTRIES}")

    # Verify struct pack format matches expected kona_ref_t size
    entry_pack_format = "<H2x3f"  # uint16_t + 2 pad + 3 floats
    actual_size = struct.calcsize(entry_pack_format)
    assert actual_size == KONA_REF_T_SIZE, \
        f"Struct pack size mismatch: got {actual_size}, expected {KONA_REF_T_SIZE}"

    # Calculate CRC32 of entry data (matching firmware struct layout)
    payload = bytearray()
    for s in sorted_swatches:
        # Pack as: uint16_t + 2 padding bytes + 3 floats (little-endian)
        payload.extend(struct.pack(entry_pack_format, s.id, s.L, s.a, s.b))
    crc = zlib.crc32(payload) & 0xFFFFFFFF

    # Generate entry lines WITH inline comments (the feature being tested)
    rows = []
    for s in sorted_swatches:
        rows.append(f"        {{ {s.id}, {s.L:.6f}f, {s.a:.6f}f, {s.b:.6f}f }}, // {s.id} {s.name}")
    
    if len(sorted_swatches) < MAX_ENTRIES:
        rows.append("        // Remaining entries are zero-initialized.")

    generated_at = dt.datetime.now(dt.timezone.utc).isoformat()
    
    return f'''// Auto-generated by kona_scanner_gui.py
// Source CSV: {csv_path}
// Generated at: {generated_at}
// Entry count: {len(sorted_swatches)}

#include "konaref.h"

const kona_table_t kona_reference = {{
    .version = KONA_REF_SCHEMA_VERSION,
    .entry_count = {len(sorted_swatches)},
    .crc32 = 0x{crc:08X}u,
    .entries = {{
{chr(10).join(rows)}
    }},
}};
'''


def test_generate_cpp_inline_comments():
    """Test that _generate_cpp adds inline comments with id and name."""
    # Create test swatches
    test_swatches = [
        SwatchData(panel="test", panel_index=1, id=449, name="SUNNY", 
                   L=50.123456, a=10.654321, b=-5.111111, measured=True),
        SwatchData(panel="test", panel_index=2, id=120, name="AZURE", 
                   L=60.222222, a=5.333333, b=15.444444, measured=True),
    ]
    
    # Generate C++ content using standalone implementation
    cpp_content = _generate_cpp_standalone(test_swatches, "/test/path.csv")
    
    # Verify that inline comments with id and name are present
    assert "// 120 AZURE" in cpp_content, "Missing inline comment for AZURE"
    assert "// 449 SUNNY" in cpp_content, "Missing inline comment for SUNNY"
    
    # Verify the full entry format (id, L, a, b with comment)
    assert "{ 120," in cpp_content, "Missing entry for id 120"
    assert "{ 449," in cpp_content, "Missing entry for id 449"
    
    # Verify the complete line format
    assert "{ 120, 60.222222f, 5.333333f, 15.444444f }, // 120 AZURE" in cpp_content, \
        "Full line format incorrect for AZURE"
    
    print("_generate_cpp inline comments test passed")


def test_generate_cpp_sorted_by_id():
    """Test that _generate_cpp sorts entries by ID."""
    # Create test swatches in unsorted order
    test_swatches = [
        SwatchData(panel="test", panel_index=1, id=300, name="THIRD", 
                   L=30.0, a=3.0, b=3.0, measured=True),
        SwatchData(panel="test", panel_index=2, id=100, name="FIRST", 
                   L=10.0, a=1.0, b=1.0, measured=True),
        SwatchData(panel="test", panel_index=3, id=200, name="SECOND", 
                   L=20.0, a=2.0, b=2.0, measured=True),
    ]
    
    cpp_content = _generate_cpp_standalone(test_swatches, "/test/path.csv")
    
    # Find positions of each entry
    pos_first = cpp_content.find("// 100 FIRST")
    pos_second = cpp_content.find("// 200 SECOND")
    pos_third = cpp_content.find("// 300 THIRD")
    
    # Verify order: FIRST < SECOND < THIRD
    assert pos_first < pos_second < pos_third, \
        f"Entries not sorted by ID: FIRST={pos_first}, SECOND={pos_second}, THIRD={pos_third}"
    
    print("_generate_cpp sorting test passed")


def test_generate_cpp_valid_cpp_syntax():
    """Test that generated C++ has valid basic syntax."""
    test_swatches = [
        SwatchData(panel="test", panel_index=1, id=1, name="TEST COLOR", 
                   L=50.0, a=0.0, b=0.0, measured=True),
    ]
    
    cpp_content = _generate_cpp_standalone(test_swatches, "/test/path.csv")
    
    # Check required C++ elements
    assert '#include "konaref.h"' in cpp_content, "Missing include statement"
    assert "const kona_table_t kona_reference = {" in cpp_content, "Missing struct declaration"
    assert ".version = KONA_REF_SCHEMA_VERSION," in cpp_content, "Missing version field"
    assert ".entry_count = 1," in cpp_content, "Missing entry_count field"
    assert ".crc32 = 0x" in cpp_content, "Missing crc32 field"
    assert ".entries = {" in cpp_content, "Missing entries field"
    assert "};" in cpp_content, "Missing closing brace"
    
    print("_generate_cpp valid C++ syntax test passed")


if __name__ == "__main__":
    test_generate_cpp_inline_comments()
    test_generate_cpp_sorted_by_id()
    test_generate_cpp_valid_cpp_syntax()
    print("\nAll kona_scanner_gui tests passed")
