// Auto-generated by scripts/generate_kona_table.py
// Source CSV: kona_avg_captures.csv
// Generated at: 2026-03-12T19:39:57.568782+00:00
// Entry count: 5

#include "konaref.h"

const kona_table_t kona_reference = {
    .version = KONA_REF_SCHEMA_VERSION,
    .entry_count = 5,
    .crc32 = 0x05211E2Bu,
    .entries = {
        { 189, 93.210700f, 10.996600f, -0.813300f },
        { 449, 86.767400f, 14.785100f, 88.852600f },
        { 496, 68.801900f, 48.894800f, 36.220800f },
        { 861, 97.907600f, 4.776000f, -3.029700f },
        { 1283, 99.591800f, 0.878500f, -1.562800f },
        // Remaining entries are zero-initialized.
    },
};
