// Auto-generated by scripts/generate_kona_table.py
// Source CSV: kona_avg_captures.csv
// Generated at: 2026-03-12T04:45:20.356909+00:00
// Entry count: 7

#include "konaref.h"

const kona_table_t kona_reference = {
    .version = KONA_REF_SCHEMA_VERSION,
    .entry_count = 7,
    .crc32 = 0x5CE878DCu,
    .entries = {
        { 149, 0.090300f, 0.020300f, 0.012700f },
        { 189, 0.090300f, 0.020300f, 0.012700f },
        { 449, 0.090300f, 0.020300f, 0.012700f },
        { 496, 0.151000f, 0.363400f, 0.117300f },
        { 861, 0.090300f, 0.020300f, 0.012700f },
        { 1283, 1.991500f, 3.689300f, 2.429200f },
        { 1849, 0.090300f, 0.020300f, 0.012700f },
        // Remaining entries are zero-initialized.
    },
};
