/**
 * @file konaref.h
 * @brief Kona Swatch Reference Table Schema and Access API
 *
 * This module provides a reference table of CIE L*a*b* color values for
 * Kona Cotton quilting fabric swatches. The table is used for high-accuracy
 * color matching when identifying fabric colors.
 *
 * The table is generated at build time from scan captures using
 * scripts/generate_kona_table.py. If no scan data is available, an empty
 * fallback table (konaref_default.cpp) is used and matching falls back
 * to the general color database.
 *
 * @note CIEDE2000 is used for matching (perceptually uniform color difference).
 * @note Default match threshold is 2.0 ΔE2000 units (just noticeable difference).
 */

#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Schema version for the Kona reference table format.
 *
 * Increment when changing the struct layout to detect incompatible tables.
 */
#define KONA_REF_SCHEMA_VERSION 1u

/**
 * @brief Maximum number of Kona swatch entries supported.
 *
 * Includes 365 real Kona Cotton swatches plus up to ~1,900 synthetic
 * tint/shade/tone variants generated by scripts/generate_synthetic_tints.py.
 */
#define KONA_REF_MAX_ENTRIES 2560u

/**
 * @brief A single Kona swatch reference entry.
 *
 * Contains the swatch ID and its measured CIE L*a*b* color coordinates.
 * These values are averages from multiple device sensor readings.
 *
 * @note The struct has 2 bytes of padding after kona_id for float alignment.
 *       Total size is 16 bytes (not 14). The build-time table generator
 *       (scripts/generate_kona_table.py) must use the same layout for CRC32.
 */
typedef struct
{
    uint16_t kona_id;   ///< Kona swatch identifier (matches KONA_SWATCH_METADATA[].id)
    // 2 bytes padding inserted by compiler for float alignment
    float l;            ///< CIE L* (lightness): 0-100
    float a;            ///< CIE a* (green-red axis): typically -128 to +127
    float b;            ///< CIE b* (blue-yellow axis): typically -128 to +127
} kona_ref_t;

/**
 * @brief Expected size of kona_ref_t struct in bytes.
 *
 * This includes 2 bytes of padding after kona_id for float alignment:
 * - uint16_t kona_id: 2 bytes
 * - padding: 2 bytes
 * - float l, a, b: 12 bytes (3 × 4 bytes)
 * - Total: 16 bytes
 */
#define KONA_REF_T_SIZE 16u

/**
 * @brief Container for the complete Kona reference table.
 *
 * Includes metadata for validation (version, count, CRC32) and the
 * array of reference entries. CRC32 covers only the entry data.
 */
typedef struct
{
    uint16_t version;       ///< Schema version (must match KONA_REF_SCHEMA_VERSION)
    uint16_t entry_count;   ///< Number of valid entries (0 to KONA_REF_MAX_ENTRIES)
    uint32_t crc32;         ///< CRC32 checksum of entries[] data (IEEE 802.3 polynomial)
    kona_ref_t entries[KONA_REF_MAX_ENTRIES]; ///< Swatch reference data
} kona_table_t;

#ifdef __cplusplus
static_assert(sizeof(kona_ref_t) == KONA_REF_T_SIZE,
              "kona_ref_t size mismatch - update KONA_REF_T_SIZE and generate_kona_table.py");
#endif

/**
 * @brief Global Kona reference table instance.
 *
 * Defined in konaref_generated.cpp (build-time generated) or
 * konaref_default.cpp (empty fallback).
 */
extern const kona_table_t kona_reference;

/**
 * @brief VP-tree node for O(log n) nearest-neighbour search.
 *
 * Each node references an entry in kona_reference.entries[] by index and
 * stores the median CIEDE2000 distance used to partition left (closer)
 * and right (farther) subtrees.
 *
 * The node array is generated alongside the reference table by
 * scripts/generate_kona_table.py and lives in Flash (const).
 */
typedef struct
{
    int16_t entry_index;       ///< Index into kona_reference.entries[]
    float   median_distance;   ///< CIEDE2000 partition threshold
    int16_t left_child;        ///< Left child node index (-1 if none)
    int16_t right_child;       ///< Right child node index (-1 if none)
} kona_vptree_node_t;

/** @brief Number of VP-tree nodes (equals kona_reference.entry_count). */
extern const uint16_t kona_vptree_node_count;

/** @brief Flat VP-tree node array (root is index 0). */
extern const kona_vptree_node_t kona_vptree_nodes[];

/**
 * @brief Synthetic nearest-name entry.
 *
 * Maps a synthetic swatch ID to the closest real-world colour name
 * from reference databases (meodai, Resene, xkcd).  Generated by
 * scripts/annotate_nearest_colors.py and embedded by
 * scripts/generate_kona_table.py.
 */
typedef struct
{
    uint16_t kona_id;          ///< Synthetic swatch identifier (≥ 10000)
    const char* nearest_name;  ///< Nearest real-world colour name
} kona_synthetic_name_t;

/** @brief Number of synthetic nearest-name entries. */
extern const uint16_t kona_synthetic_name_count;

/** @brief Sorted array of synthetic nearest-name entries. */
extern const kona_synthetic_name_t kona_synthetic_names[];

/**
 * @brief Swatch description entry.
 *
 * Maps a swatch ID to a human-written natural-language description of
 * the colour's visual impression.  Generated from the "description"
 * field in kona_captures.json / kona_synthetic_tints.json by
 * scripts/generate_kona_table.py.
 */
typedef struct
{
    uint16_t kona_id;              ///< Swatch identifier
    const char* description;       ///< One-sentence colour description
} kona_description_t;

/** @brief Number of swatch description entries. */
extern const uint16_t kona_description_count;

/** @brief Sorted array of swatch description entries. */
extern const kona_description_t kona_descriptions[];

/**
 * @brief Validate the Kona reference table integrity.
 *
 * Checks schema version, entry count bounds, and CRC32 checksum.
 *
 * @return true if table is valid and ready for matching, false otherwise.
 */
bool kona_ref_validate(void);

/**
 * @brief Get the number of entries in the Kona reference table.
 *
 * @return Entry count (0 if table is empty or invalid).
 */
size_t kona_ref_entry_count(void);

/**
 * @brief Get a pointer to the Kona reference entries array.
 *
 * @return Pointer to the entries array (valid up to kona_ref_entry_count() entries).
 */
const kona_ref_t* kona_ref_entries(void);

/**
 * @brief Find the closest Kona reference entry using the VP-tree.
 *
 * Performs an O(log n) nearest-neighbour search via the pre-built VP-tree.
 * Falls back to a linear scan if the VP-tree is empty or unavailable.
 *
 * @param[in]  query_l   Query CIE L* value.
 * @param[in]  query_a   Query CIE a* value.
 * @param[in]  query_b   Query CIE b* value.
 * @param[out] delta_e   CIEDE2000 distance to the best match (may be NULL).
 * @param[out] best_idx  Index of the best match in entries[] (may be NULL).
 * @return Pointer to the closest kona_ref_t entry, or NULL if the table is empty.
 */
const kona_ref_t* kona_ref_find_closest(float query_l, float query_a, float query_b,
                                        float* delta_e, size_t* best_idx);

/**
 * @brief Look up the nearest real-world colour name for a synthetic swatch.
 *
 * Performs a linear scan of the synthetic nearest-name table generated by
 * scripts/annotate_nearest_colors.py.
 *
 * @param[in] kona_id  Synthetic swatch identifier (≥ 10000).
 * @return The nearest colour name string, or NULL if not found.
 */
const char* kona_ref_synthetic_name(uint16_t kona_id);

/**
 * @brief Look up the natural-language description for a swatch.
 *
 * Performs a binary search of the description table generated by
 * scripts/generate_kona_table.py.
 *
 * @param[in] kona_id  Swatch identifier.
 * @return The description string, or NULL if not found.
 */
const char* kona_ref_description(uint16_t kona_id);

#ifdef __cplusplus
}
#endif
