// Auto-generated by kona_scanner_gui.py
// Source CSV: /home/yam/esp/shade_sayer/kona_365_sensor_ready.csv
// Generated at: 2026-03-13T20:35:07.195238+00:00
// Entry count: 12

#include "konaref.h"

const kona_table_t kona_reference = {
    .version = KONA_REF_SCHEMA_VERSION,
    .entry_count = 12,
    .crc32 = 0x2545E112u,
    .entries = {
        { 59, 98.500000f, 66.308800f, 90.075200f }, // 59 CANTALOUPE
        { 84, 98.500000f, 101.179800f, 110.000000f }, // 84 PERSIMMON
        { 149, 98.500000f, 37.309000f, 110.000000f }, // 149 PAPAYA
        { 192, 98.500000f, 68.645500f, 103.460600f }, // 192 MANGO
        { 410, 98.500000f, 106.341900f, 110.000000f }, // 410 KUMQUAT
        { 449, 98.500000f, 26.026400f, 110.000000f }, // 449 SUNNY
        { 1265, 98.500000f, 92.815700f, 110.000000f }, // 1265 ORANGE
        { 1320, 98.500000f, 61.591200f, 110.000000f }, // 1320 SAFFRON
        { 1482, 98.500000f, 61.496100f, 110.000000f }, // 1482 SCHOOL BUS
        { 1839, 98.500000f, 97.621700f, 110.000000f }, // 1839 CLEMENTINE
        { 1848, 98.500000f, 99.459300f, 110.000000f }, // 1848 MARMALADE
        { 1849, 98.500000f, 45.164000f, 110.000000f }, // 1849 NACHO CHEESE
        // Remaining entries are zero-initialized.
    },
};
