#!/usr/bin/env python3
"""Generate a Kona reference data C++ table from kona_365_sensor_ready.csv.

This script reads Lab measurements from the Kona 365 sensor-ready CSV file and
produces a C++ source file containing a kona_table_t struct for firmware use.
Only rows with measured=true and complete L/a/b values are included.

The generated table includes:
- Schema version for compatibility checking
- Entry count and CRC32 checksum for validation
- Lab values for each measured Kona swatch

Usage:
    python3 generate_kona_table.py --input ../kona_365_sensor_ready.csv \\
                                   --output ../main/konaref_generated.cpp
"""

import argparse
import csv
import dataclasses
import datetime as dt
import pathlib
import struct
import zlib
from typing import Iterable, List, Optional

SCHEMA_VERSION = 1
MAX_ENTRIES = 365


@dataclasses.dataclass(frozen=True)
class KonaEntry:
    """A single Kona swatch reference entry."""
    kona_id: int
    l: float
    a: float
    b: float
    name: str = ""


def _float_or_none(row: dict, key: str) -> Optional[float]:
    """Parse a float from a CSV row, returning None for missing/empty values."""
    value = row.get(key, "")
    if value is None or str(value).strip() == "":
        return None
    return float(value)


def parse_sensor_ready_csv(path: pathlib.Path) -> List[KonaEntry]:
    """Parse Lab measurements from a kona_365_sensor_ready.csv file.
    
    Expected columns: id, name, L, a, b, measured
    Only rows where measured=true and L/a/b are all present are included.
    Duplicate IDs are deduplicated (last row wins).
    Output is sorted by kona_id.
    """
    entries = {}
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            kona_id_raw = row.get("id", "").strip()
            if not kona_id_raw:
                continue

            measured = row.get("measured", "").strip().lower() == "true"
            if not measured:
                continue

            l = _float_or_none(row, "L")
            a = _float_or_none(row, "a")
            b = _float_or_none(row, "b")
            if l is None or a is None or b is None:
                continue

            kona_id = int(kona_id_raw)
            entries[kona_id] = KonaEntry(
                kona_id=kona_id,
                l=l,
                a=a,
                b=b,
                name=row.get("name", "").strip(),
            )

    ordered = sorted(entries.values(), key=lambda e: e.kona_id)
    if len(ordered) > MAX_ENTRIES:
        raise ValueError(f"Too many entries ({len(ordered)}), max is {MAX_ENTRIES}")
    return ordered


def crc32_entries(entries: Iterable[KonaEntry]) -> int:
    """Compute CRC32 checksum of entry data matching firmware struct layout.
    
    The binary format must match kona_ref_t in konaref.h:
    - uint16_t kona_id (2 bytes)
    - 2 bytes padding (for 4-byte float alignment)
    - float l, a, b (4 bytes each = 12 bytes)
    - Total: 16 bytes per entry, little-endian
    
    Note: The padding is required because C/C++ struct alignment rules
    insert 2 bytes of padding after kona_id to align the float members.
    """
    payload = bytearray()
    for e in entries:
        # Pack as: uint16_t + 2 padding bytes + 3 floats (little-endian)
        # This must match sizeof(kona_ref_t) = 16 bytes
        payload.extend(struct.pack("<H2x3f", e.kona_id, e.l, e.a, e.b))
    return zlib.crc32(payload) & 0xFFFFFFFF


def render_cpp(entries: List[KonaEntry], csv_path: pathlib.Path, source_script: str = "generate_kona_table.py") -> str:
    """Render the C++ source file containing the kona_table_t struct."""
    sorted_entries = sorted(entries, key=lambda e: e.kona_id)
    if len(sorted_entries) > MAX_ENTRIES:
        raise ValueError(f"Too many entries ({len(sorted_entries)}), max is {MAX_ENTRIES}")
    crc = crc32_entries(sorted_entries)
    rows = []
    for e in sorted_entries:
        comment = f" // {e.kona_id} {e.name}".rstrip() if e.name else f" // {e.kona_id}"
        rows.append(
            "        { %d, %.6ff, %.6ff, %.6ff },%s" % (
                e.kona_id,
                e.l,
                e.a,
                e.b,
                comment,
            )
        )
    if len(sorted_entries) < MAX_ENTRIES:
        rows.append("        // Remaining entries are zero-initialized.")

    generated_at = dt.datetime.now(dt.timezone.utc).isoformat()
    return f'''// Auto-generated by {source_script}
// Source CSV: {csv_path}
// Generated at: {generated_at}
// Entry count: {len(sorted_entries)}

#include "konaref.h"

const kona_table_t kona_reference = {{
    .version = KONA_REF_SCHEMA_VERSION,
    .entry_count = {len(sorted_entries)},
    .crc32 = 0x{crc:08X}u,
    .entries = {{
{chr(10).join(rows)}
    }},
}};
'''


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", default="../kona_365_sensor_ready.csv", type=pathlib.Path,
                   help="Input kona_365_sensor_ready.csv file with measured Lab values")
    p.add_argument("--output", default=pathlib.Path("../main/konaref_generated.cpp"), type=pathlib.Path,
                   help="Output C++ source file path")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    entries = parse_sensor_ready_csv(args.input)
    output_text = render_cpp(entries, args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output_text)
    print(f"Wrote {len(entries)} entries to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
