#!/usr/bin/env python3
"""Generate a Kona reference C++ table from kona_avg_captures.csv."""

import argparse
import csv
import dataclasses
import datetime as dt
import pathlib
import struct
import zlib
from typing import Iterable, List

SCHEMA_VERSION = 1
MAX_ENTRIES = 365


@dataclasses.dataclass(frozen=True)
class KonaEntry:
    kona_id: int
    l: float
    a: float
    b: float
    sigma_l: float
    sigma_a: float
    sigma_b: float


def _float_from(row: dict, key: str) -> float:
    value = row.get(key, "")
    if value is None or value == "":
        return 0.0
    return float(value)


def parse_capture_csv(path: pathlib.Path) -> List[KonaEntry]:
    entries = {}
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            kona_id_raw = row.get("kona_id", "").strip()
            if not kona_id_raw:
                continue

            kona_id = int(kona_id_raw)
            entries[kona_id] = KonaEntry(
                kona_id=kona_id,
                l=_float_from(row, "mean_lab_l"),
                a=_float_from(row, "mean_lab_a"),
                b=_float_from(row, "mean_lab_b"),
                sigma_l=_float_from(row, "stddev_xyz_x"),
                sigma_a=_float_from(row, "stddev_xyz_y"),
                sigma_b=_float_from(row, "stddev_xyz_z"),
            )

    ordered = sorted(entries.values(), key=lambda e: e.kona_id)
    if len(ordered) > MAX_ENTRIES:
        raise ValueError(f"Too many entries ({len(ordered)}), max is {MAX_ENTRIES}")
    return ordered


def crc32_entries(entries: Iterable[KonaEntry]) -> int:
    payload = bytearray()
    for e in entries:
        payload.extend(struct.pack("<H6f", e.kona_id, e.l, e.a, e.b, e.sigma_l, e.sigma_a, e.sigma_b))
    return zlib.crc32(payload) & 0xFFFFFFFF


def render_cpp(entries: List[KonaEntry], csv_path: pathlib.Path) -> str:
    crc = crc32_entries(entries)
    rows = []
    for e in entries:
        rows.append(
            "        { %d, %.6ff, %.6ff, %.6ff, %.6ff, %.6ff, %.6ff }," % (
                e.kona_id,
                e.l,
                e.a,
                e.b,
                e.sigma_l,
                e.sigma_a,
                e.sigma_b,
            )
        )
    if len(entries) < MAX_ENTRIES:
        rows.append("        // Remaining entries are zero-initialized.")

    generated_at = dt.datetime.now(dt.timezone.utc).isoformat()
    return f'''// Auto-generated by scripts/generate_kona_table.py
// Source CSV: {csv_path}
// Generated at: {generated_at}

#include "konaref.h"

const kona_table_t kona_reference = {{
    .version = KONA_REF_SCHEMA_VERSION,
    .entry_count = {len(entries)},
    .crc32 = 0x{crc:08X}u,
    .entries = {{
{chr(10).join(rows)}
    }},
}};
'''


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", default="kona_avg_captures.csv", type=pathlib.Path)
    p.add_argument("--output", default=pathlib.Path("../main/konaref.cpp"), type=pathlib.Path)
    return p.parse_args()


def main() -> int:
    args = parse_args()
    entries = parse_capture_csv(args.input)
    output_text = render_cpp(entries, args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output_text)
    print(f"Wrote {len(entries)} entries to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
