#!/usr/bin/env python3
"""Generate a Kona reference data C++ table from kona_avg_captures.csv.

This script reads averaged Lab measurements from a CSV file (generated by
kona_scan_collect.py from device scan sessions) and produces a C++ source
file containing a kona_table_t struct for firmware use.

The generated table includes:
- Schema version for compatibility checking
- Entry count and CRC32 checksum for validation
- Lab values for each measured Kona swatch

Usage:
    python3 generate_kona_table.py --input kona_avg_captures.csv \\
                                   --output ../main/konaref_generated.cpp
"""

import argparse
import csv
import dataclasses
import datetime as dt
import pathlib
import struct
import zlib
from typing import Iterable, List

SCHEMA_VERSION = 1
MAX_ENTRIES = 365


@dataclasses.dataclass(frozen=True)
class KonaEntry:
    """A single Kona swatch reference entry."""
    kona_id: int
    l: float
    a: float
    b: float


def _float_from(row: dict, key: str) -> float:
    """Parse a float from a CSV row, defaulting to 0.0 for missing/empty values."""
    value = row.get(key, "")
    if value is None or value == "":
        return 0.0
    return float(value)


def parse_capture_csv(path: pathlib.Path) -> List[KonaEntry]:
    """Parse averaged Lab measurements from a capture CSV file.
    
    Expected columns: kona_id, mean_lab_l, mean_lab_a, mean_lab_b
    Duplicate IDs are deduplicated (last row wins).
    Output is sorted by kona_id.
    """
    entries = {}
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            kona_id_raw = row.get("kona_id", "").strip()
            if not kona_id_raw:
                continue

            kona_id = int(kona_id_raw)
            entries[kona_id] = KonaEntry(
                kona_id=kona_id,
                l=_float_from(row, "mean_lab_l"),
                a=_float_from(row, "mean_lab_a"),
                b=_float_from(row, "mean_lab_b"),
            )

    ordered = sorted(entries.values(), key=lambda e: e.kona_id)
    if len(ordered) > MAX_ENTRIES:
        raise ValueError(f"Too many entries ({len(ordered)}), max is {MAX_ENTRIES}")
    return ordered


def crc32_entries(entries: Iterable[KonaEntry]) -> int:
    """Compute CRC32 checksum of entry data matching firmware struct layout.
    
    The binary format must match kona_ref_t in konaref.h:
    - uint16_t kona_id (2 bytes)
    - 2 bytes padding (for 4-byte float alignment)
    - float l, a, b (4 bytes each = 12 bytes)
    - Total: 16 bytes per entry, little-endian
    
    Note: The padding is required because C/C++ struct alignment rules
    insert 2 bytes of padding after kona_id to align the float members.
    """
    payload = bytearray()
    for e in entries:
        # Pack as: uint16_t + 2 padding bytes + 3 floats (little-endian)
        # This must match sizeof(kona_ref_t) = 16 bytes
        payload.extend(struct.pack("<H2x3f", e.kona_id, e.l, e.a, e.b))
    return zlib.crc32(payload) & 0xFFFFFFFF


def render_cpp(entries: List[KonaEntry], csv_path: pathlib.Path) -> str:
    """Render the C++ source file containing the kona_table_t struct."""
    crc = crc32_entries(entries)
    rows = []
    for e in entries:
        rows.append(
            "        { %d, %.6ff, %.6ff, %.6ff }," % (
                e.kona_id,
                e.l,
                e.a,
                e.b,
            )
        )
    if len(entries) < MAX_ENTRIES:
        rows.append("        // Remaining entries are zero-initialized.")

    generated_at = dt.datetime.now(dt.timezone.utc).isoformat()
    return f'''// Auto-generated by scripts/generate_kona_table.py
// Source CSV: {csv_path}
// Generated at: {generated_at}
// Entry count: {len(entries)}

#include "konaref.h"

const kona_table_t kona_reference = {{
    .version = KONA_REF_SCHEMA_VERSION,
    .entry_count = {len(entries)},
    .crc32 = 0x{crc:08X}u,
    .entries = {{
{chr(10).join(rows)}
    }},
}};
'''


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", default="kona_avg_captures.csv", type=pathlib.Path,
                   help="Input CSV file with averaged Lab measurements")
    p.add_argument("--output", default=pathlib.Path("../main/konaref_generated.cpp"), type=pathlib.Path,
                   help="Output C++ source file path")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    entries = parse_capture_csv(args.input)
    output_text = render_cpp(entries, args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output_text)
    print(f"Wrote {len(entries)} entries to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
